services:
  db:
    image: postgres:15
    restart: always
    container_name: skywalk-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: skywalk_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: nest-backend
    depends_on:
      - db
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
      JWT_SECRET: skywalk-secret-key
      JWT_EXPIRES_IN: 1h
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: skywalk_db

volumes:
  pgdata:
