import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1775840020658 implements MigrationInterface {
    name = 'InitialSchema1775840020658'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "continent" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "iso_code" character(2), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_55bb303499ba2319afe214396a1" UNIQUE ("name"), CONSTRAINT "UQ_17aebd954bc31323f680569dd0e" UNIQUE ("iso_code"), CONSTRAINT "PK_1d0d8f1398cdebe7f83068b269c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "city" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "latitude" numeric(10,8), "longitude" numeric(11,8), "population" integer, "timezone" character varying(100), "is_capital" boolean NOT NULL DEFAULT false, "image_url" text, "country_id" integer NOT NULL, CONSTRAINT "PK_b222f51ce26f7e5ca86944a6739" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "country" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "iso_code" character(2), "continent_id" integer NOT NULL, CONSTRAINT "UQ_d8a20ea179fa742827ea45f270e" UNIQUE ("iso_code"), CONSTRAINT "PK_bf6e37c231c4f4ea56dcd887269" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "admin_procedure" ("id" SERIAL NOT NULL, "procedure_type" character varying(100) NOT NULL, "description" text, "category" character varying, "step_order" integer, "average_delay_days" integer, "country_id" integer NOT NULL, CONSTRAINT "PK_318daf81daf383614d95a02a993" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "travel_type" ("id" SERIAL NOT NULL, "name" character varying(50) NOT NULL, CONSTRAINT "PK_e0737ca37d4cc9a9dac31e66e53" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "expatriation_project" ("id" SERIAL NOT NULL, "objective" character varying(100), "expected_duration" integer, "budget" numeric(10,2), "status" character varying(50) NOT NULL DEFAULT 'planning', "expected_departure_date" date, "user_id" integer NOT NULL, "travel_type_id" integer, "destination_country_id" integer NOT NULL, "destination_city_id" integer, CONSTRAINT "PK_5f9200867d6691cde6cf62ec729" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "procedure_tracking" ("id" SERIAL NOT NULL, "status" character varying(50) NOT NULL DEFAULT 'in_progress', "start_date" date, "end_date" date, "user_id" integer NOT NULL, "admin_procedure_id" integer NOT NULL, "project_id" integer NOT NULL, CONSTRAINT "PK_b27e34ba8de9d33043a9ffcbf0f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "app_user" ("id" SERIAL NOT NULL, "firstname" character varying(50), "lastname" character varying(50), "email" character varying(255) NOT NULL, "password" character varying(255) NOT NULL, "roles" character varying(50) NOT NULL DEFAULT 'user', "age" integer, "country_origin_id" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_3fa909d0e37c531ebc237703391" UNIQUE ("email"), CONSTRAINT "PK_22a5c4a3d9b2fb8e4e73fc4ada1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "language" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, CONSTRAINT "PK_cc0a99e710eb3733f6fb42b1d4c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_language" ("user_id" integer NOT NULL, "language_id" integer NOT NULL, "level" character varying(50) NOT NULL, CONSTRAINT "PK_44d235663fb8c4f753eaca3ab6d" PRIMARY KEY ("user_id", "language_id"))`);
        await queryRunner.query(`CREATE TABLE "resource" ("id" SERIAL NOT NULL, "title" character varying(255) NOT NULL, "url" character varying(500), "resource_type" character varying(50), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "country_id" integer NOT NULL, CONSTRAINT "PK_e2894a5867e06ae2e8889f1173f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "visa_requirement" ("id" SERIAL NOT NULL, "origin_country_id" integer NOT NULL, "destination_country_id" integer NOT NULL, "visa_type" character varying(100) NOT NULL, "duration_days" integer, "description" text, CONSTRAINT "PK_9e94e8640a4625e423e13e8a8ae" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "document" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, CONSTRAINT "PK_e57d3357f83f3cdc0acffc3d777" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "procedure_document" ("admin_procedure_id" integer NOT NULL, "document_id" integer NOT NULL, CONSTRAINT "PK_04e0c4573331a01cf8e5933d483" PRIMARY KEY ("admin_procedure_id", "document_id"))`);
        await queryRunner.query(`CREATE TABLE "notification" ("id" SERIAL NOT NULL, "notif_type" character varying(50) NOT NULL, "message" text NOT NULL, "is_read" boolean NOT NULL DEFAULT false, "sent_at" TIMESTAMP NOT NULL DEFAULT now(), "user_id" integer NOT NULL, CONSTRAINT "PK_705b6c7cdf9b2c2ff7ac7872cb7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."newsletter_subscriber_status_enum" AS ENUM('ACTIVE', 'UNSUBSCRIBED')`);
        await queryRunner.query(`CREATE TABLE "newsletter_subscriber" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "status" "public"."newsletter_subscriber_status_enum" NOT NULL DEFAULT 'ACTIVE', "source" character varying NOT NULL DEFAULT 'landing_page', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_c7c77fa243eefb2415b13f1b4e4" UNIQUE ("email"), CONSTRAINT "PK_673f5f9a16ef0e216059224e02f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "business_sector" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "description" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_7571d1f134a02311d6b6679a4e1" UNIQUE ("name"), CONSTRAINT "PK_bafc14b5306f366c07fceee367a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "job_offer" ("id_offer" SERIAL NOT NULL, "job_title" character varying(255) NOT NULL, "company_name" character varying(255), "average_salary" numeric(10,2), "description" text, "publication_date" date NOT NULL DEFAULT ('now'::text)::date, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "city_id" integer NOT NULL, "sector_id" integer, CONSTRAINT "PK_a5b2b109fa0901ec0d919887842" PRIMARY KEY ("id_offer"))`);
        await queryRunner.query(`CREATE TABLE "guide" ("id" SERIAL NOT NULL, "title" character varying(255) NOT NULL, "content" text NOT NULL, "guide_type" character varying(50), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "country_id" integer NOT NULL, CONSTRAINT "PK_fe92b4af32150e0580d37eacaef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "currency" ("id" SERIAL NOT NULL, "code" character varying(10) NOT NULL, "symbol" character varying(10) NOT NULL, CONSTRAINT "PK_3cda65c731a6264f0e444cc9b91" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "country_language" ("country_id" integer NOT NULL, "language_id" integer NOT NULL, "is_official" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_88e6036a2e5c0caa33b279a69ee" PRIMARY KEY ("country_id", "language_id"))`);
        await queryRunner.query(`CREATE TABLE "country_currency" ("country_id" integer NOT NULL, "currency_id" integer NOT NULL, "is_primary" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_26e7795feb1d60e040b910c3a5b" PRIMARY KEY ("country_id", "currency_id"))`);
        await queryRunner.query(`CREATE TABLE "forum_message" ("id" SERIAL NOT NULL, "content" text NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "topic_id" integer NOT NULL, "user_id" integer NOT NULL, CONSTRAINT "PK_bdf04e2e4ed23139798bbb2c950" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "forum_topic" ("id" SERIAL NOT NULL, "title" character varying(255) NOT NULL, "category" character varying(50), "views_count" integer NOT NULL DEFAULT '0', "is_pinned" boolean NOT NULL DEFAULT false, "is_locked" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "user_id" integer NOT NULL, "country_id" integer, CONSTRAINT "PK_b5bd8bbfc742fe036e175fff5a6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "forum_report" ("id" SERIAL NOT NULL, "reason" character varying(50) NOT NULL, "details" text, "status" character varying(20) NOT NULL DEFAULT 'pending', "moderator_note" text, "resolved_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "reporter_id" integer NOT NULL, "message_id" integer, "topic_id" integer, "moderator_id" integer, CONSTRAINT "PK_c77cbc9f1136831201bc79d1c71" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "experience" ("id" SERIAL NOT NULL, "title" character varying(255), "description" text, "rating" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "user_id" integer NOT NULL, "country_id" integer NOT NULL, CONSTRAINT "CHK_c6f1807d063dd814eb96e63b45" CHECK ("rating" >= 1 AND "rating" <= 5), CONSTRAINT "PK_5e8d5a534100e1b17ee2efa429a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "country_content" ("id" SERIAL NOT NULL, "title" character varying(255) NOT NULL, "url" character varying(255) NOT NULL, "content_type" character varying NOT NULL, "country_id" integer NOT NULL, CONSTRAINT "PK_5fa3e4d059ead17c400c4bdf0d7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cost_of_living" ("id" SERIAL NOT NULL, "average_rent" numeric(10,2), "monthly_transport" numeric(10,2), "food_expenses" numeric(10,2), "public_services" numeric(10,2), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "city_id" integer NOT NULL, CONSTRAINT "PK_dd2c0691fc429d71ad0f0a922cd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cost_of_living_cache" ("id" SERIAL NOT NULL, "city_id" integer NOT NULL, "data" jsonb NOT NULL, "cached_at" TIMESTAMP NOT NULL DEFAULT now(), "expires_at" TIMESTAMP NOT NULL, CONSTRAINT "REL_07d1d7486590b5d127dedf4d72" UNIQUE ("city_id"), CONSTRAINT "PK_3a050ac92002d784ab3f7e51ef0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "city_comparison" ("id" SERIAL NOT NULL, "user_id" integer NOT NULL, "city_id" integer NOT NULL, CONSTRAINT "PK_527259cf251be252b78b68e7a9b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "checklist" ("id" SERIAL NOT NULL, "title" character varying(255) NOT NULL, "steps" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "country_id" integer NOT NULL, CONSTRAINT "PK_e4b437f5107f2a9d5b744d4eb4c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "city" ADD CONSTRAINT "FK_08af2eeb576770524fa05e26f39" FOREIGN KEY ("country_id") REFERENCES "country"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "country" ADD CONSTRAINT "FK_5029f36b1de4667226bd738c404" FOREIGN KEY ("continent_id") REFERENCES "continent"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin_procedure" ADD CONSTRAINT "FK_94bde5dd4c942c6a788bfbe847b" FOREIGN KEY ("country_id") REFERENCES "country"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expatriation_project" ADD CONSTRAINT "FK_52b87e3c504d2dbd58630d6b2a7" FOREIGN KEY ("user_id") REFERENCES "app_user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expatriation_project" ADD CONSTRAINT "FK_41d66aca61b9835c2342059b626" FOREIGN KEY ("travel_type_id") REFERENCES "travel_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expatriation_project" ADD CONSTRAINT "FK_b023bf52e39f946e3978a44b706" FOREIGN KEY ("destination_country_id") REFERENCES "country"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expatriation_project" ADD CONSTRAINT "FK_1f1893f0ffab59962ae578fa11b" FOREIGN KEY ("destination_city_id") REFERENCES "city"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "procedure_tracking" ADD CONSTRAINT "FK_c34a3fe3d910f7c9f8e60b6d597" FOREIGN KEY ("user_id") REFERENCES "app_user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "procedure_tracking" ADD CONSTRAINT "FK_288e66bed362bcb73bd28631101" FOREIGN KEY ("admin_procedure_id") REFERENCES "admin_procedure"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "procedure_tracking" ADD CONSTRAINT "FK_85bb443d1bf1f34f95f7ab5d621" FOREIGN KEY ("project_id") REFERENCES "expatriation_project"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "app_user" ADD CONSTRAINT "FK_bda4c299c455898f7bfc50d103a" FOREIGN KEY ("country_origin_id") REFERENCES "country"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_language" ADD CONSTRAINT "FK_0d0733d623941fe5668fa1c7dfa" FOREIGN KEY ("user_id") REFERENCES "app_user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_language" ADD CONSTRAINT "FK_5dfa2fd919fc492ca143502d705" FOREIGN KEY ("language_id") REFERENCES "language"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "resource" ADD CONSTRAINT "FK_1b2f1a1b85dc8f8af93869019b0" FOREIGN KEY ("country_id") REFERENCES "country"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "visa_requirement" ADD CONSTRAINT "FK_e0f66ed3314b8057928eba83677" FOREIGN KEY ("origin_country_id") REFERENCES "country"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "visa_requirement" ADD CONSTRAINT "FK_f09ac4e245564149819d7c2bb47" FOREIGN KEY ("destination_country_id") REFERENCES "country"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "procedure_document" ADD CONSTRAINT "FK_167f5e17d1168af167ba0c4fcb2" FOREIGN KEY ("admin_procedure_id") REFERENCES "admin_procedure"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "procedure_document" ADD CONSTRAINT "FK_956fdf6864b096f587fbf508924" FOREIGN KEY ("document_id") REFERENCES "document"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification" ADD CONSTRAINT "FK_928b7aa1754e08e1ed7052cb9d8" FOREIGN KEY ("user_id") REFERENCES "app_user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_offer" ADD CONSTRAINT "FK_7049ab4881e9d2c68edd4b72bd7" FOREIGN KEY ("city_id") REFERENCES "city"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_offer" ADD CONSTRAINT "FK_2d9e3b89c230a2879a3c3519c89" FOREIGN KEY ("sector_id") REFERENCES "business_sector"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guide" ADD CONSTRAINT "FK_c6a9522aa1c4ad8a6e209a82991" FOREIGN KEY ("country_id") REFERENCES "country"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "country_language" ADD CONSTRAINT "FK_a15def1924cf72a829f13d43c2d" FOREIGN KEY ("country_id") REFERENCES "country"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "country_language" ADD CONSTRAINT "FK_d7dce10beca55ecd8c7e50d7ce5" FOREIGN KEY ("language_id") REFERENCES "language"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "country_currency" ADD CONSTRAINT "FK_c5bdf51ffac5ccc4e24e37c4f97" FOREIGN KEY ("country_id") REFERENCES "country"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "country_currency" ADD CONSTRAINT "FK_615b737952f56cdf7e459364b11" FOREIGN KEY ("currency_id") REFERENCES "currency"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "forum_message" ADD CONSTRAINT "FK_bb9e67251430d09539f97b67095" FOREIGN KEY ("topic_id") REFERENCES "forum_topic"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "forum_message" ADD CONSTRAINT "FK_f44374405c3512cd5d7f1aeadd9" FOREIGN KEY ("user_id") REFERENCES "app_user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "forum_topic" ADD CONSTRAINT "FK_8c676de0c6ad474ceebdb547571" FOREIGN KEY ("user_id") REFERENCES "app_user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "forum_topic" ADD CONSTRAINT "FK_476a9c58c8cb88ee9c1f5fdd1db" FOREIGN KEY ("country_id") REFERENCES "country"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "forum_report" ADD CONSTRAINT "FK_3df0f73c0e0a37c63943cd1e828" FOREIGN KEY ("reporter_id") REFERENCES "app_user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "forum_report" ADD CONSTRAINT "FK_2b888d1b3ed8a2aa96b3923e4bd" FOREIGN KEY ("message_id") REFERENCES "forum_message"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "forum_report" ADD CONSTRAINT "FK_bca6d27d6f69233612a4ecee2bf" FOREIGN KEY ("topic_id") REFERENCES "forum_topic"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "forum_report" ADD CONSTRAINT "FK_812cdff9d4dbf8e116474d033ea" FOREIGN KEY ("moderator_id") REFERENCES "app_user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "experience" ADD CONSTRAINT "FK_62c0623650986849f3fc1d148e7" FOREIGN KEY ("user_id") REFERENCES "app_user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "experience" ADD CONSTRAINT "FK_20a0d6b01fbb6b045344a1c7b9c" FOREIGN KEY ("country_id") REFERENCES "country"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "country_content" ADD CONSTRAINT "FK_37b4cd91e8f2ca2d37242e02e3a" FOREIGN KEY ("country_id") REFERENCES "country"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cost_of_living" ADD CONSTRAINT "FK_0582b7c576e0c9a3c7cffd092d1" FOREIGN KEY ("city_id") REFERENCES "city"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cost_of_living_cache" ADD CONSTRAINT "FK_07d1d7486590b5d127dedf4d723" FOREIGN KEY ("city_id") REFERENCES "city"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "city_comparison" ADD CONSTRAINT "FK_812e386ed117c745c9f8d8d3e6b" FOREIGN KEY ("user_id") REFERENCES "app_user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "city_comparison" ADD CONSTRAINT "FK_718687433b504c27e8cd22af944" FOREIGN KEY ("city_id") REFERENCES "city"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "checklist" ADD CONSTRAINT "FK_d352258e8f5055f7cb105db1891" FOREIGN KEY ("country_id") REFERENCES "country"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "checklist" DROP CONSTRAINT "FK_d352258e8f5055f7cb105db1891"`);
        await queryRunner.query(`ALTER TABLE "city_comparison" DROP CONSTRAINT "FK_718687433b504c27e8cd22af944"`);
        await queryRunner.query(`ALTER TABLE "city_comparison" DROP CONSTRAINT "FK_812e386ed117c745c9f8d8d3e6b"`);
        await queryRunner.query(`ALTER TABLE "cost_of_living_cache" DROP CONSTRAINT "FK_07d1d7486590b5d127dedf4d723"`);
        await queryRunner.query(`ALTER TABLE "cost_of_living" DROP CONSTRAINT "FK_0582b7c576e0c9a3c7cffd092d1"`);
        await queryRunner.query(`ALTER TABLE "country_content" DROP CONSTRAINT "FK_37b4cd91e8f2ca2d37242e02e3a"`);
        await queryRunner.query(`ALTER TABLE "experience" DROP CONSTRAINT "FK_20a0d6b01fbb6b045344a1c7b9c"`);
        await queryRunner.query(`ALTER TABLE "experience" DROP CONSTRAINT "FK_62c0623650986849f3fc1d148e7"`);
        await queryRunner.query(`ALTER TABLE "forum_report" DROP CONSTRAINT "FK_812cdff9d4dbf8e116474d033ea"`);
        await queryRunner.query(`ALTER TABLE "forum_report" DROP CONSTRAINT "FK_bca6d27d6f69233612a4ecee2bf"`);
        await queryRunner.query(`ALTER TABLE "forum_report" DROP CONSTRAINT "FK_2b888d1b3ed8a2aa96b3923e4bd"`);
        await queryRunner.query(`ALTER TABLE "forum_report" DROP CONSTRAINT "FK_3df0f73c0e0a37c63943cd1e828"`);
        await queryRunner.query(`ALTER TABLE "forum_topic" DROP CONSTRAINT "FK_476a9c58c8cb88ee9c1f5fdd1db"`);
        await queryRunner.query(`ALTER TABLE "forum_topic" DROP CONSTRAINT "FK_8c676de0c6ad474ceebdb547571"`);
        await queryRunner.query(`ALTER TABLE "forum_message" DROP CONSTRAINT "FK_f44374405c3512cd5d7f1aeadd9"`);
        await queryRunner.query(`ALTER TABLE "forum_message" DROP CONSTRAINT "FK_bb9e67251430d09539f97b67095"`);
        await queryRunner.query(`ALTER TABLE "country_currency" DROP CONSTRAINT "FK_615b737952f56cdf7e459364b11"`);
        await queryRunner.query(`ALTER TABLE "country_currency" DROP CONSTRAINT "FK_c5bdf51ffac5ccc4e24e37c4f97"`);
        await queryRunner.query(`ALTER TABLE "country_language" DROP CONSTRAINT "FK_d7dce10beca55ecd8c7e50d7ce5"`);
        await queryRunner.query(`ALTER TABLE "country_language" DROP CONSTRAINT "FK_a15def1924cf72a829f13d43c2d"`);
        await queryRunner.query(`ALTER TABLE "guide" DROP CONSTRAINT "FK_c6a9522aa1c4ad8a6e209a82991"`);
        await queryRunner.query(`ALTER TABLE "job_offer" DROP CONSTRAINT "FK_2d9e3b89c230a2879a3c3519c89"`);
        await queryRunner.query(`ALTER TABLE "job_offer" DROP CONSTRAINT "FK_7049ab4881e9d2c68edd4b72bd7"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP CONSTRAINT "FK_928b7aa1754e08e1ed7052cb9d8"`);
        await queryRunner.query(`ALTER TABLE "procedure_document" DROP CONSTRAINT "FK_956fdf6864b096f587fbf508924"`);
        await queryRunner.query(`ALTER TABLE "procedure_document" DROP CONSTRAINT "FK_167f5e17d1168af167ba0c4fcb2"`);
        await queryRunner.query(`ALTER TABLE "visa_requirement" DROP CONSTRAINT "FK_f09ac4e245564149819d7c2bb47"`);
        await queryRunner.query(`ALTER TABLE "visa_requirement" DROP CONSTRAINT "FK_e0f66ed3314b8057928eba83677"`);
        await queryRunner.query(`ALTER TABLE "resource" DROP CONSTRAINT "FK_1b2f1a1b85dc8f8af93869019b0"`);
        await queryRunner.query(`ALTER TABLE "user_language" DROP CONSTRAINT "FK_5dfa2fd919fc492ca143502d705"`);
        await queryRunner.query(`ALTER TABLE "user_language" DROP CONSTRAINT "FK_0d0733d623941fe5668fa1c7dfa"`);
        await queryRunner.query(`ALTER TABLE "app_user" DROP CONSTRAINT "FK_bda4c299c455898f7bfc50d103a"`);
        await queryRunner.query(`ALTER TABLE "procedure_tracking" DROP CONSTRAINT "FK_85bb443d1bf1f34f95f7ab5d621"`);
        await queryRunner.query(`ALTER TABLE "procedure_tracking" DROP CONSTRAINT "FK_288e66bed362bcb73bd28631101"`);
        await queryRunner.query(`ALTER TABLE "procedure_tracking" DROP CONSTRAINT "FK_c34a3fe3d910f7c9f8e60b6d597"`);
        await queryRunner.query(`ALTER TABLE "expatriation_project" DROP CONSTRAINT "FK_1f1893f0ffab59962ae578fa11b"`);
        await queryRunner.query(`ALTER TABLE "expatriation_project" DROP CONSTRAINT "FK_b023bf52e39f946e3978a44b706"`);
        await queryRunner.query(`ALTER TABLE "expatriation_project" DROP CONSTRAINT "FK_41d66aca61b9835c2342059b626"`);
        await queryRunner.query(`ALTER TABLE "expatriation_project" DROP CONSTRAINT "FK_52b87e3c504d2dbd58630d6b2a7"`);
        await queryRunner.query(`ALTER TABLE "admin_procedure" DROP CONSTRAINT "FK_94bde5dd4c942c6a788bfbe847b"`);
        await queryRunner.query(`ALTER TABLE "country" DROP CONSTRAINT "FK_5029f36b1de4667226bd738c404"`);
        await queryRunner.query(`ALTER TABLE "city" DROP CONSTRAINT "FK_08af2eeb576770524fa05e26f39"`);
        await queryRunner.query(`DROP TABLE "checklist"`);
        await queryRunner.query(`DROP TABLE "city_comparison"`);
        await queryRunner.query(`DROP TABLE "cost_of_living_cache"`);
        await queryRunner.query(`DROP TABLE "cost_of_living"`);
        await queryRunner.query(`DROP TABLE "country_content"`);
        await queryRunner.query(`DROP TABLE "experience"`);
        await queryRunner.query(`DROP TABLE "forum_report"`);
        await queryRunner.query(`DROP TABLE "forum_topic"`);
        await queryRunner.query(`DROP TABLE "forum_message"`);
        await queryRunner.query(`DROP TABLE "country_currency"`);
        await queryRunner.query(`DROP TABLE "country_language"`);
        await queryRunner.query(`DROP TABLE "currency"`);
        await queryRunner.query(`DROP TABLE "guide"`);
        await queryRunner.query(`DROP TABLE "job_offer"`);
        await queryRunner.query(`DROP TABLE "business_sector"`);
        await queryRunner.query(`DROP TABLE "newsletter_subscriber"`);
        await queryRunner.query(`DROP TYPE "public"."newsletter_subscriber_status_enum"`);
        await queryRunner.query(`DROP TABLE "notification"`);
        await queryRunner.query(`DROP TABLE "procedure_document"`);
        await queryRunner.query(`DROP TABLE "document"`);
        await queryRunner.query(`DROP TABLE "visa_requirement"`);
        await queryRunner.query(`DROP TABLE "resource"`);
        await queryRunner.query(`DROP TABLE "user_language"`);
        await queryRunner.query(`DROP TABLE "language"`);
        await queryRunner.query(`DROP TABLE "app_user"`);
        await queryRunner.query(`DROP TABLE "procedure_tracking"`);
        await queryRunner.query(`DROP TABLE "expatriation_project"`);
        await queryRunner.query(`DROP TABLE "travel_type"`);
        await queryRunner.query(`DROP TABLE "admin_procedure"`);
        await queryRunner.query(`DROP TABLE "country"`);
        await queryRunner.query(`DROP TABLE "city"`);
        await queryRunner.query(`DROP TABLE "continent"`);
    }

}
