import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Import de la liste LDNOOBW (FR + EN) dans forbidden_word, en sévérité `medium`
 * (= publié mais flaggé + avertissement, jamais bloqué d'office). Les admins
 * escaladent au cas par cas en high/critical. Insert-only (ON CONFLICT DO NOTHING) :
 * ne touche ni aux mots du lot de démarrage ni aux réglages admin existants.
 * Source: github.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words
 */
export class ImportLdnoobwWords1782190000000 implements MigrationInterface {
  name = 'ImportLdnoobwWords1782190000000';

  private readonly words: string[] = [
  "2 girls 1 cup",
  "2g1c",
  "acrotomophilia",
  "alabama hot pocket",
  "alaskan pipeline",
  "anal",
  "anilingus",
  "anus",
  "apeshit",
  "arsehole",
  "ass",
  "asshole",
  "assmunch",
  "auto erotic",
  "autoerotic",
  "babeland",
  "baby batter",
  "baby juice",
  "baiser",
  "ball gag",
  "ball gravy",
  "ball kicking",
  "ball licking",
  "ball sack",
  "ball sucking",
  "bander",
  "bangbros",
  "bangbus",
  "bareback",
  "barely legal",
  "barenaked",
  "bastard",
  "bastardo",
  "bastinado",
  "bbw",
  "bdsm",
  "beaner",
  "beaners",
  "beastiality",
  "beaver cleaver",
  "beaver lips",
  "bestiality",
  "big black",
  "big breasts",
  "big knockers",
  "big tits",
  "bigornette",
  "bimbos",
  "birdlock",
  "bitch",
  "bitches",
  "bite",
  "bitte",
  "black cock",
  "bloblos",
  "blonde action",
  "blonde on blonde action",
  "blow job",
  "blow your load",
  "blowjob",
  "blue waffle",
  "blumpkin",
  "bollocks",
  "bondage",
  "boner",
  "boob",
  "boobs",
  "booty call",
  "bordel",
  "bourré",
  "bourrée",
  "brackmard",
  "branlage",
  "branler",
  "branlette",
  "branleur",
  "branleuse",
  "brouter le cresson",
  "brown showers",
  "brunette action",
  "bukkake",
  "bulldyke",
  "bullet vibe",
  "bullshit",
  "bung hole",
  "bunghole",
  "busty",
  "butt",
  "buttcheeks",
  "butthole",
  "caca",
  "camel toe",
  "camgirl",
  "camslut",
  "camwhore",
  "carpet muncher",
  "carpetmuncher",
  "chatte",
  "chiasse",
  "chier",
  "chiottes",
  "chocolate rosebuds",
  "cialis",
  "circlejerk",
  "cleveland steamer",
  "clit",
  "clito",
  "clitoris",
  "clover clamps",
  "clusterfuck",
  "cock",
  "cocks",
  "con",
  "connard",
  "connasse",
  "conne",
  "coon",
  "coons",
  "coprolagnia",
  "coprophilia",
  "cornhole",
  "couilles",
  "cramouille",
  "creampie",
  "cul",
  "cum",
  "cumming",
  "cumshot",
  "cumshots",
  "cunnilingus",
  "cunt",
  "darkie",
  "date rape",
  "daterape",
  "deep throat",
  "deepthroat",
  "dendrophilia",
  "dick",
  "dildo",
  "dingleberries",
  "dingleberry",
  "dirty pillows",
  "dirty sanchez",
  "dog style",
  "doggie style",
  "doggiestyle",
  "doggy style",
  "doggystyle",
  "dolcett",
  "domination",
  "dominatrix",
  "dommes",
  "donkey punch",
  "double dong",
  "double penetration",
  "dp action",
  "dry hump",
  "dvda",
  "déconne",
  "déconner",
  "eat my ass",
  "ecchi",
  "ejaculation",
  "emmerdant",
  "emmerder",
  "emmerdeur",
  "emmerdeuse",
  "enculeur",
  "enculeurs",
  "enculé",
  "enculée",
  "enfoiré",
  "enfoirée",
  "erotic",
  "erotism",
  "escort",
  "eunuch",
  "fag",
  "faggot",
  "fecal",
  "felch",
  "fellatio",
  "feltch",
  "female squirting",
  "femdom",
  "figging",
  "fille de pute",
  "fils de pute",
  "fingerbang",
  "fingering",
  "fisting",
  "folle",
  "foot fetish",
  "footjob",
  "foutre",
  "frotting",
  "fuck",
  "fuck buttons",
  "fuckin",
  "fucking",
  "fucktards",
  "fudge packer",
  "fudgepacker",
  "futanari",
  "g-spot",
  "gang bang",
  "gangbang",
  "gay sex",
  "genitals",
  "gerbe",
  "gerber",
  "giant cock",
  "girl on",
  "girl on top",
  "girls gone wild",
  "goatcx",
  "goatse",
  "god damn",
  "gokkun",
  "golden shower",
  "goo girl",
  "goodpoop",
  "goregasm",
  "gouine",
  "grande folle",
  "grogniasse",
  "grope",
  "group sex",
  "gueule",
  "guro",
  "hand job",
  "handjob",
  "hard core",
  "hardcore",
  "hentai",
  "homoerotic",
  "honkey",
  "hooker",
  "horny",
  "hot carl",
  "hot chick",
  "how to kill",
  "how to murder",
  "huge fat",
  "humping",
  "incest",
  "intercourse",
  "jack off",
  "jail bait",
  "jailbait",
  "jelly donut",
  "jerk off",
  "jigaboo",
  "jiggaboo",
  "jiggerboo",
  "jizz",
  "jouir",
  "juggs",
  "kike",
  "kinbaku",
  "kinkster",
  "kinky",
  "knobbing",
  "la putain de ta mère",
  "leather restraint",
  "leather straight jacket",
  "lemon party",
  "livesex",
  "lolita",
  "lovemaking",
  "make me come",
  "male squirting",
  "malpt",
  "masturbate",
  "masturbating",
  "masturbation",
  "menage a trois",
  "merde",
  "merdeuse",
  "merdeux",
  "meuf",
  "milf",
  "missionary position",
  "mong",
  "motherfucker",
  "mound of venus",
  "mr hands",
  "muff diver",
  "muffdiving",
  "ménage à trois",
  "nambla",
  "nawashi",
  "negro",
  "neonazi",
  "nig nog",
  "nigga",
  "nigger",
  "nimphomania",
  "nipple",
  "nipples",
  "nique ta mère",
  "nique ta race",
  "nsfw",
  "nsfw images",
  "nude",
  "nudity",
  "nutten",
  "nympho",
  "nymphomania",
  "nègre",
  "octopussy",
  "omorashi",
  "one cup two girls",
  "one guy one jar",
  "orgasm",
  "orgy",
  "paedophile",
  "paki",
  "palucher",
  "panties",
  "panty",
  "pedobear",
  "pedophile",
  "pegging",
  "penis",
  "phone sex",
  "piece of shit",
  "pikey",
  "pipi",
  "piss pig",
  "pisser",
  "pissing",
  "pisspig",
  "playboy",
  "pleasure chest",
  "pole smoker",
  "ponyplay",
  "poof",
  "poon",
  "poontang",
  "poop chute",
  "poopchute",
  "porn",
  "porno",
  "pornography",
  "pouffiasse",
  "pousse-crotte",
  "prince albert piercing",
  "pthc",
  "pubes",
  "punany",
  "pussy",
  "putain",
  "pute",
  "pédale",
  "pédé",
  "péter",
  "queaf",
  "queef",
  "quim",
  "raghead",
  "raging boner",
  "ramoner",
  "rape",
  "raping",
  "rapist",
  "rectum",
  "reverse cowgirl",
  "rimjob",
  "rimming",
  "rosy palm",
  "rosy palm and her 5 sisters",
  "rusty trombone",
  "s&m",
  "sac à foutre",
  "sac à merde",
  "sadism",
  "salaud",
  "salope",
  "santorum",
  "scat",
  "schlong",
  "scissoring",
  "semen",
  "sex",
  "sexcam",
  "sexo",
  "sexual",
  "sexuality",
  "sexually",
  "sexy",
  "shaved beaver",
  "shaved pussy",
  "shemale",
  "shibari",
  "shit",
  "shitblimp",
  "shitty",
  "shota",
  "shrimping",
  "skeet",
  "slanteye",
  "slut",
  "smut",
  "snatch",
  "snowballing",
  "sodomize",
  "sodomy",
  "spastic",
  "spic",
  "splooge",
  "splooge moose",
  "spooge",
  "spread legs",
  "spunk",
  "strap on",
  "strapon",
  "strappado",
  "strip club",
  "style doggy",
  "suce",
  "suck",
  "sucks",
  "suicide girls",
  "sultry women",
  "swastika",
  "swinger",
  "tainted love",
  "tanche",
  "tapette",
  "taste my",
  "tea bagging",
  "teuch",
  "threesome",
  "throating",
  "thumbzilla",
  "tied up",
  "tight white",
  "tit",
  "tits",
  "titties",
  "titty",
  "tongue in a",
  "topless",
  "tosser",
  "towelhead",
  "tranny",
  "tribadism",
  "tringler",
  "trique",
  "troncher",
  "trou du cul",
  "tub girl",
  "tubgirl",
  "turlute",
  "tushy",
  "twat",
  "twink",
  "twinkie",
  "two girls one cup",
  "undressing",
  "upskirt",
  "urethra play",
  "urophilia",
  "vagina",
  "venus mound",
  "viagra",
  "vibrator",
  "violet wand",
  "vorarephilia",
  "voyeur",
  "voyeurweb",
  "voyuer",
  "vulva",
  "wank",
  "wet dream",
  "wetback",
  "white power",
  "whore",
  "worldsex",
  "wrapping men",
  "wrinkled starfish",
  "xx",
  "xxx",
  "yaoi",
  "yellow showers",
  "yiffy",
  "zigounette",
  "zizi",
  "zoophilia",
  "étron",
  "🖕"
];

  public async up(queryRunner: QueryRunner): Promise<void> {
    for (const word of this.words) {
      await queryRunner.query(
        `INSERT INTO "forbidden_word" ("word", "severity", "is_active")
         VALUES ($1, 'medium', TRUE)
         ON CONFLICT ("word") DO NOTHING`,
        [word],
      );
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // N'annule que l'import (mots encore en 'medium'), pas les escalades admin.
    await queryRunner.query(
      `DELETE FROM "forbidden_word" WHERE "word" = ANY($1) AND "severity" = 'medium'`,
      [this.words],
    );
  }
}
